### ISSUE TITLE
[bug] wayfarer fails on Arch Wayland (Gnome Shell & Hyrpland)

### ISSUE THREAD

**Issue by coffebar** [stronnag/wayfarer#1]
Env: Arch Wayland (Hyprland)

It seems start recording, but there are no files in target directory.

> Out => /home/abc/Video/Wayfarer_2023-02-11_095447.mkv
> pipeline = queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=5 ! queue ! vp8enc min_quantizer=10 max_quantizer=13 cpu-used=5 deadline=1000000 threads=5 ! queue ! matroskamux name=mux name=mux ! filesink name=filesink location="/home/abc/Video/Wayfarer_2023-02-11_095447.mkv" pipewiresrc fd=8 path=85 do-timestamp=true keepalive-time=1000 resend-last=true  ! video/x-raw, max-framerate=30/1 ! queue0. pulsesrc device="default" ! opusenc  ! queue ! mux.
> 
> (wayfarer:483453): GLib-GObject-CRITICAL **: 09:54:47.365: g_object_new_is_valid_property: property 'name' for type 'GstMatroskaMux' cannot be set twice
> 
> (wayfarer:483453): GStreamer-WARNING **: 09:54:47.375: Trying to link elements videoconvert0 and queue0 that don't share a common ancestor: queue0 hasn't been added to a bin or pipeline, and videoconvert0 is in pipeline0
> 
> (wayfarer:483453): GStreamer-WARNING **: 09:54:47.375: Trying to link elements videoconvert0 and queue0 that don't share a common ancestor: queue0 hasn't been added to a bin or pipeline, and videoconvert0 is in pipeline0
> 
> (wayfarer:483453): GStreamer-WARNING **: 09:54:47.375: Trying to link elements queue0 and vp8enc0 that don't share a common ancestor: queue0 hasn't been added to a bin or pipeline, but vp8enc0 is in pipeline0
> 
> (wayfarer:483453): GStreamer-WARNING **: 09:54:47.375: Trying to link elements queue0 and vp8enc0 that don't share a common ancestor: queue0 hasn't been added to a bin or pipeline, but vp8enc0 is in pipeline0
> Error: no element "pipewiresrc"
> 
> (wayfarer:483453): GStreamer-CRITICAL **: 09:54:49.150: gst_element_send_event: assertion 'GST_IS_ELEMENT (element)' failed

If i switch to x11 session, this issue is not there (video saving ok).

**Comment by stronnag** [comment]
To quote the project README:

> wayfarer is a screen recorder for GNOME                                     
>                                                                            
>  • Modern GNOME desktop (Arch, Fedora, Debian Testing, Ubuntu 22.04)         
>  • Wayland or Xorg                                                           
>  • Pipewire / Pusleaudio / libportal (XDG Desktop Portal)                    
>  • Wireplumber recommended                                                   
>                                                                           
>  Does not support other desktops.  

So I'm not surprised that it doesn't work in this environment, nor that  it does in X11 because that has no dependencies on different Wayland compositors and portals.

I will update the README to make it clearer (and fix the `pusle` typo).

**Comment by stronnag** [comment]
It's also a generic issue. Doesn't work in Gnome Shell either. I'll have a look at what's changed ...

**Comment by stronnag** [comment]
Interestingly, other 3rd party tools like `kooha` fail in exactly the same way.

**Comment by coffebar** [comment]
kooha works for me without this issue

**Comment by stronnag** [comment]
> kooha works for me without this issue

Indeed, once I upgraded my ancient version. 

This is probably the end of road for `wayfarer`; I no longer have to time or energy to chase every changing APIs.

**Comment by stronnag** [comment]
> This is probably the end of road for `wayfarer`; I no longer have to time or energy to chase every changing APIs.

Fortunately, it isn't. The development branch works again with latest GStreamer ...
