### ISSUE TITLE
meson.build:1:0: ERROR: Could not execute Vala compiler: valac

### ISSUE THREAD

**Issue by Kr666you** [stronnag/wayfarer#11]
raspiuser@raspberrypi:~/Desktop/wayfarer-master $ meson setup build --buildtype=release --prefix=~/.local
The Meson build system
Version: 1.0.1
Source dir: /home/raspiuser/Desktop/wayfarer-master
Build dir: /home/raspiuser/Desktop/wayfarer-master/build
Build type: native build
Project name: wayfarer
Project version: 1.2.1
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
C linker for the host machine: cc ld.bfd 2.40

meson.build:1:0: ERROR: Could not execute Vala compiler: valac

A full log can be found at /home/raspiuser/Desktop/wayfarer-master/build/meson-logs/meson-log.txt
raspiuser@raspberrypi:~/Desktop/wayfarer-master $ 

here is the full log:

Build started at 2023-12-27T19:23:31.749792
Main binary: /usr/bin/python3
Build Options: '-Dprefix=~/.local' -Dbuildtype=release
Python system: Linux
The Meson build system
Version: 1.0.1
Source dir: /home/raspiuser/Desktop/wayfarer-master
Build dir: /home/raspiuser/Desktop/wayfarer-master/build
Build type: native build
Project name: wayfarer
Project version: 1.2.1
-----
Detecting compiler via: cc --version
compiler returned <Popen: returncode: 0 args: ['cc', '--version']>
compiler stdout:
cc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

compiler stderr:

Running command: cc -E -dM -
-----
Detecting linker via: cc -Wl,--version
linker returned <Popen: returncode: 0 args: ['cc', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils for Debian) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 12.2.0
/usr/bin/ld -plugin /usr/lib/gcc/aarch64-linux-gnu/12/liblto_plugin.so -plugin-opt=/usr/lib/gcc/aarch64-linux-gnu/12/lto-wrapper -plugin-opt=-fresolution=/tmp/ccNK57Px.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr --hash-style=gnu --as-needed -dynamic-linker /lib/ld-linux-aarch64.so.1 -X -EL -maarch64linux --fix-cortex-a53-843419 -pie /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/Scrt1.o /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/crti.o /usr/lib/gcc/aarch64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/aarch64-linux-gnu/12 -L/usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu -L/usr/lib/gcc/aarch64-linux-gnu/12/../../../../lib -L/lib/aarch64-linux-gnu -L/lib/../lib -L/usr/lib/aarch64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/aarch64-linux-gnu/12/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/aarch64-linux-gnu/12/crtendS.o /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/crtn.o

Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/raspiuser/Desktop/wayfarer-master/build/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
C linker for the host machine: cc ld.bfd 2.40

meson.build:1:0: ERROR: Could not execute Vala compiler: valac

**Comment by stronnag** [comment]
Works just fine on my Rpi (Arch Linux). Seems like either your OS is just broken, or you're not installed the dependencies; in particular valac.

**Comment by Kr666you** [comment]
i installed valac but now i get this error:
meson/meson.build:1:0: ERROR: Command `/usr/bin/pkg-config --modversion gtk4` failed with status 1.

full log:
Build started at 2023-12-28T16:48:31.525767
Main binary: /usr/bin/python3
Build Options: '-Dprefix=~/.local' -Dbuildtype=release
Python system: Linux
The Meson build system
Version: 1.0.1
Source dir: /home/raspiuser/Desktop/wayfarer-master
Build dir: /home/raspiuser/Desktop/wayfarer-master/build
Build type: native build
Project name: wayfarer
Project version: 1.2.1
-----
Detecting compiler via: cc --version
compiler returned <Popen: returncode: 0 args: ['cc', '--version']>
compiler stdout:
cc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


compiler stderr:

Running command: cc -E -dM -
-----
Detecting linker via: cc -Wl,--version
linker returned <Popen: returncode: 0 args: ['cc', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils for Debian) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 12.2.0
/usr/bin/ld -plugin /usr/lib/gcc/aarch64-linux-gnu/12/liblto_plugin.so -plugin-opt=/usr/lib/gcc/aarch64-linux-gnu/12/lto-wrapper -plugin-opt=-fresolution=/tmp/ccM4DD9k.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr --hash-style=gnu --as-needed -dynamic-linker /lib/ld-linux-aarch64.so.1 -X -EL -maarch64linux --fix-cortex-a53-843419 -pie /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/Scrt1.o /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/crti.o /usr/lib/gcc/aarch64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/aarch64-linux-gnu/12 -L/usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu -L/usr/lib/gcc/aarch64-linux-gnu/12/../../../../lib -L/lib/aarch64-linux-gnu -L/lib/../lib -L/usr/lib/aarch64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/aarch64-linux-gnu/12/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/aarch64-linux-gnu/12/crtendS.o /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/crtn.o

Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/raspiuser/Desktop/wayfarer-master/build/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
C linker for the host machine: cc ld.bfd 2.40
Running compile:
Working directory:  /tmp/tmplp8hbd1e
Command line:  valac /tmp/tmplp8hbd1e/testfile.vala -C 

Code:
 class MesonSanityCheck : Object { }
Compiler stdout:
 
Compiler stderr:
 
Vala compiler for the host machine: valac (valac 0.56.3)
-----
Detecting compiler via: cc --version
compiler returned <Popen: returncode: 0 args: ['cc', '--version']>
compiler stdout:
cc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


compiler stderr:

Running command: cc -E -dM -
-----
Detecting linker via: cc -Wl,--version
linker returned <Popen: returncode: 0 args: ['cc', '-Wl,--version']>
linker stdout:
GNU ld (GNU Binutils for Debian) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

linker stderr:
collect2 version 12.2.0
/usr/bin/ld -plugin /usr/lib/gcc/aarch64-linux-gnu/12/liblto_plugin.so -plugin-opt=/usr/lib/gcc/aarch64-linux-gnu/12/lto-wrapper -plugin-opt=-fresolution=/tmp/ccGn3ojO.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr --hash-style=gnu --as-needed -dynamic-linker /lib/ld-linux-aarch64.so.1 -X -EL -maarch64linux --fix-cortex-a53-843419 -pie /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/Scrt1.o /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/crti.o /usr/lib/gcc/aarch64-linux-gnu/12/crtbeginS.o -L/usr/lib/gcc/aarch64-linux-gnu/12 -L/usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu -L/usr/lib/gcc/aarch64-linux-gnu/12/../../../../lib -L/lib/aarch64-linux-gnu -L/lib/../lib -L/usr/lib/aarch64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/aarch64-linux-gnu/12/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/aarch64-linux-gnu/12/crtendS.o /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/crtn.o

Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /home/raspiuser/Desktop/wayfarer-master/build/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 12.2.0 "cc (Debian 12.2.0-14) 12.2.0")
C linker for the build machine: cc ld.bfd 2.40
Using cached compile:
Cached command line:  valac /tmp/tmplp8hbd1e/testfile.vala -C 

Code:
 class MesonSanityCheck : Object { }
Cached compiler stdout:
 
Cached compiler stderr:
 
Vala compiler for the build machine: valac (valac 0.56.3)
Build machine cpu family: aarch64
Build machine cpu: aarch64
Host machine cpu family: aarch64
Host machine cpu: aarch64
Target machine cpu family: aarch64
Target machine cpu: aarch64
Running command: /usr/bin/python3 meson/baseinfo.py
--- stdout ---
Debian GNU/Linux : Linux-6.1.0-rpi7-rpi-2712-aarch64-with-glibc2.36

--- stderr ---


Message: Debian GNU/Linux : Linux-6.1.0-rpi7-rpi-2712-aarch64-with-glibc2.36
Configuring wayfarer-config.h using configuration
Fallback to subproject blueprint-compiler which provides program blueprint-compiler

Executing subproject blueprint-compiler 

Project name: blueprint-compiler
Project version: 0.10.1
Program python3 found: YES (/usr/bin/python3)
Configuring blueprint-compiler.pc using configuration
Configuring blueprint-compiler using configuration
Program blueprint-compiler found: YES (/home/raspiuser/Desktop/wayfarer-master/build/subprojects/blueprint-compiler/blueprint-compiler)
Adding test "tests"
Build targets in project: 1
Subproject blueprint-compiler finished.

Program blueprint-compiler found: YES (overridden)
Pkg-config binary for 0 is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
stdout:
2.74.6
-----------
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
stdout:
-I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include
-----------
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
stdout:
-L/usr/lib/aarch64-linux-gnu -lglib-2.0
-----------
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs glib-2.0` -> 0
stdout:
-lglib-2.0
-----------
Running compile:
Working directory:  /home/raspiuser/Desktop/wayfarer-master/build/meson-private/tmpvao2q2k8
Command line:  cc /home/raspiuser/Desktop/wayfarer-master/build/meson-private/tmpvao2q2k8/testfile.c -o /home/raspiuser/Desktop/wayfarer-master/build/meson-private/tmpvao2q2k8/output.exe -D_FILE_OFFSET_BITS=64 -O0 

Code:
 #include<stdio.h>
        
        int main(void) {
            printf("%ld\n", (long)(sizeof(void *)));
            return 0;
        }
Compiler stdout:
 
Compiler stderr:
 
Program stdout:

8

Program stderr:


Running compile:
Working directory:  /home/raspiuser/Desktop/wayfarer-master/build/meson-private/tmppampybfi
Command line:  cc /home/raspiuser/Desktop/wayfarer-master/build/meson-private/tmppampybfi/testfile.c -o /home/raspiuser/Desktop/wayfarer-master/build/meson-private/tmppampybfi/output.obj -c -D_FILE_OFFSET_BITS=64 -O0 --print-search-dirs 

Code:
 
Compiler stdout:
 install: /usr/lib/gcc/aarch64-linux-gnu/12/
programs: =/usr/lib/gcc/aarch64-linux-gnu/12/:/usr/lib/gcc/aarch64-linux-gnu/12/:/usr/lib/gcc/aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/12/:/usr/lib/gcc/aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/aarch64-linux-gnu/12/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/bin/
libraries: =/usr/lib/gcc/aarch64-linux-gnu/12/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/lib/aarch64-linux-gnu/12/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/lib/aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/lib/../lib/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/12/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../lib/:/lib/aarch64-linux-gnu/12/:/lib/aarch64-linux-gnu/:/lib/../lib/:/usr/lib/aarch64-linux-gnu/12/:/usr/lib/aarch64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../../aarch64-linux-gnu/lib/:/usr/lib/gcc/aarch64-linux-gnu/12/../../../:/lib/:/usr/lib/

Compiler stderr:
 
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Running command: /usr/bin/pkg-config --modversion gtk4
--- stdout ---

--- stderr ---
Package gtk4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk4', required by 'virtual:world', not found



meson/meson.build:1:0: ERROR: Command `/usr/bin/pkg-config --modversion gtk4` failed with status 1.

**Comment by eli-schwartz** [comment]
The README.md clearly states:

Requires:

    Gtk 4

    Vala

    Gstreamer 1.0

    libpulse-mainloop-glib (libpulse-dev on Debian et al.)

    (optional, otherwise installed locally by the build system), Blueprint (Gtk Builder compiler).

    XDG Portal (at run time)

So simply install all of those? The error message says you don't have gtk4 installed, the README tells you that gtk4 is a requirement, there's really no point in asking humans to repeat "you don't have gtk4 installed" in a github issue.

That is the purpose of a README.

**Comment by Kr666you** [comment]
but when i try to install gtk4 it shows the same error but with different .pc files missing and when i opened the pkg-config path there was nothing inside (the path i opened was the same path that was set)
