### ISSUE TITLE
Cannot view recorded mp4 files

### ISSUE THREAD

**Issue by DmitryDGD** [stronnag/wayfarer#13]
Hello! Manjaro linux KDE wayland. The program records fine, but there is one problem. It does not play the mp4 recording file. (other formats work fine). I attach recording file and player errors (tried smplayer and vlc, as well as upload video to telegram). At the same time other mp4 files (just video or recorded by other programs on Xorg) work and play.

> /usr/bin/mpv --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-bb0 --msg-level=ffmpeg/demuxer=error --video-rotate=no --no-config --no-fs --hwdec=no --sub-auto=fuzzy --vo=xv,x11, --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=25165847 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=85 --cache=auto --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/ynwa/Изображения/smplayer_screenshots --audio-pitch-correction=yes --volume-max=110 --term-playing-msg=MPV_VERSION=${=mpv-version:}
> INFO_VIDEO_WIDTH=${=width}
> INFO_VIDEO_HEIGHT=${=height}
> INFO_VIDEO_ASPECT=${=video-params/aspect}
> INFO_VIDEO_FPS=${=container-fps:${=fps}}
> INFO_VIDEO_FORMAT=${=video-format}
> INFO_VIDEO_CODEC=${=video-format}
> INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
> INFO_AUDIO_FORMAT=${=audio-codec-name}
> INFO_AUDIO_CODEC=${=audio-codec-name}
> INFO_AUDIO_RATE=${=audio-params/samplerate}
> INFO_AUDIO_NCH=${=audio-params/channel-count}
> INFO_LENGTH=${=duration:${=length}}
> INFO_DEMUXER=${=current-demuxer:${=demuxer}}
> INFO_SEEKABLE=${=seekable}
> INFO_TITLES=${=disc-titles}
> INFO_CHAPTERS=${=chapters}
> INFO_TRACKS_COUNT=${=track-list/count}
> METADATA_TITLE=${metadata/by-key/title:}
> METADATA_ARTIST=${metadata/by-key/artist:}
> METADATA_ALBUM=${metadata/by-key/album:}
> METADATA_GENRE=${metadata/by-key/genre:}
> METADATA_DATE=${metadata/by-key/date:}
> METADATA_TRACK=${metadata/by-key/track:}
> METADATA_COPYRIGHT=${metadata/by-key/copyright:}
> INFO_MEDIA_TITLE=${=media-title:}
> INFO_STREAM_PATH=${stream-path}
>  --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} /home/ynwa/Видео/Wayfarer_2024-01-16_122139.mp4
> 
> [ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
> [lavf] avformat_open_input() failed
> [ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
> [lavf] avformat_open_input() failed
> Failed to recognize file format.
> Exiting... (Errors when loading file)

https://github.com/stronnag/wayfarer/assets/60581708/33d70360-3ab5-45f4-acac-ef93e345b592

**Comment by stronnag** [comment]
Indeed, we're not waiting for Gstreamer to report EndofStream. 
Fix soon.
