### ISSUE TITLE
Failed to record on Arch Linux / Sway

### ISSUE THREAD

**Issue by piperfw** [stronnag/wayfarer#17]
Installed `wayfarer-git` from AUR

After selecting source, when press Record a message "Failed to record" appears in GUI. A separate record window may open but remains stuck at 0:00.

The following output is given (I have audio speakers and a webcam, `pipewire` installed)
```
initial webm
Version Info: v1.2.3 (383715e, master, 2024-03-20T17:28:00+00:00)
Build Info: 2024-03-27T08:40:48Z Linux 6.8.1-arch1-1 x86_64 archmachine2, gcc version 13.2.1 20230801 (GCC)  / GNU ld (GNU Binutils) 2.42.0 / Vala 0.56.16
*DBG* fdlist 1
*DBG* Start with WAYFARER_PW_SESSION_WAYLAND 16
Media: webm
Capture audio: true
Full screen: false
Frame rate: 30
Audio rate: 48000
Audiodevice: alsa_input.usb-046d_HD_Pro_Webcam_C920_4D371EEF-02.analog-stereo
Area: (0, 0) (0, 0)
fd: 16
Source: {nodeid=58 w=1920 h=1080 x=0 y=0 source-type=2}
crop: left 0, top 0, right 1920 bottom 1080
videoscale_filter video/x-raw, width=(int)1920, height=(int)1080
scale link fails
```

**Comment by stronnag** [comment]
This is a **GNOME** application (as per README). No other DM / compositor  is supported.
Unfortunately, there is no consistency between the `xdg_desktop_portal` implementations across the different DMs / compositors and supporting anything other than the  gnome portal is not currently planned.

OTOH, I understand that `kooha` now supports wlroots based desktops, so maybe that will work for you.

**Comment by piperfw** [comment]
Ah apologies, I may submit an update to the arch wiki as the entry there reads as if wayland support is separate to GNOME

**Comment by stronnag** [comment]
Now I remember; if you run the development branch (you'll need to pull and build from github) there is an extra option `--my-portal-is-broken` which allows it to work on portals that don't correctly (IMO) implement the XDG portal standard.

If I use this option on my VisionFive (`labwc` WM with `wlroots`) then wayfarer works correctly.

**Comment by stronnag** [comment]
The above option has existed for some time, I should really back port it to master.
Any chance you could try it on `sway`?

**Comment by piperfw** [comment]
Sure, I'll try this shortly!

kooha does run, thank you for the rec., but I was hoping for an alternative as for me at least seems to become unstable for long recordings (diminishing bit rate, garbled audio)

**Comment by stronnag** [comment]
Thanks, I'm pretty confident it will work, as it's been working on the VF5 / labwc / wlroots since December (and I forgot I'd done it).
I wouldn't expect much difference v. kooha; both applications are using gstreamer to do the heavy lifting.

**Comment by piperfw** [comment]
Worked immediately as you predicted. 

With multihead setup Set Source region select didn't work as expected (selecting a region on one monitor would record the corresponding region of another!), but Set Source with fullscreen did.

Audio and video seem good. I'm going to leave running to see if I encounter similar issues as I did with Kooha.

**Comment by stronnag** [comment]
OK, master is now updated to work automagically on `wlroots`. 
I'm closing this again.
Thanks for reminding me I needed to backport this.
