### ISSUE TITLE
Tag versions after 1.1.0

### ISSUE THREAD

**Issue by fgaz** [stronnag/wayfarer#18]
It seems like git tags for versions after 1.1.0 are not present. Could you add them? It would aid in packaging.

**Comment by stronnag** [comment]
Well that's because there's releases since, mainly because it's a "push and forget" project.
As the last master commit seems to be working well, even on non-GNOME platforms, I'll fake a release and tag it.

**Comment by stronnag** [comment]
Tagged current master as 1.2.4.

**Comment by fgaz** [comment]
Thank you!
