### ISSUE TITLE
Build dependencies on ubuntu

### ISSUE THREAD

**Issue by JohannesBuchner** [stronnag/wayfarer#19]
Just in case it is helpful for others, I managed to get this to build after installing these packages on ubuntu 24.04:

```sudo apt install meson valac libglib2.0-dev libgtk2.0-dev libpoppler-glib-dev libdbus-glib-1-dev libgstreamer1.0-dev libglade2-dev libsqlite3-dev libgnome-desktop-3-dev libgnome-menu-3-dev libgirepository1.0-dev gobject-introspection libgtk-4-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libpulse-mainloop-glib0 libpulse-dev```

Maybe this could be added to the readme.

**Comment by stronnag** [comment]
You list is somewhat inappropriate. There is no dependency on packages for gtk2, poppler, sqlite, gnome*3 at least. I do not have such packages installed on my Debian and Ubuntu VMs that can build wayfarer.

As wayfarer supports numerous Linux distros and FreeBSD it would be onerous to include precise dependencies for each potential OS and a maintenance burden. The extant README and meson should be sufficient to work out what is needed.

**Comment by stronnag** [comment]
And for the record, should anyone come here looking for Debian (Ubuntu et al) dependencies, I think they look something like:

* build-essential
* valac
* meson
*  ninja-build
*  libgtk-4-dev
*  gobject-introspection 
* libgirepository1.0-dev 
* libgstreamer1.0-dev 
* libgstreamer-plugins-base1.0-dev 
* libpulse-mainloop-glib0 
* libpulse-dev
