### ISSUE TITLE
Set Source selection tool not opening fullscreen.

### ISSUE THREAD

**Issue by mcourteaux** [stronnag/wayfarer#22]
I know very little about Wayland, but the selection utility behaves like a normal window instead of something that covers the whole screen to let you select an area.

By the way: [`slurp`](https://github.com/emersion/slurp) does a great job creating a selection tool.

DE: Hyperland commit 97444ed7 (very recent)

**Comment by mcourteaux** [comment]
Can you at least give a word of explanation? wayfarer is not usable right now...

**Comment by stronnag** [comment]
Clue's in the protect title. "for **GNOME**". 
I'm not aware of any other technique for GNOME's compositor (other than the  "miniature view snapshot"  used by `kooha`.

Patches that do not affect the fundamental GNOME usage not be declined, but I'm not wasting my time on other DMs in which I have zero interest. And last time I checked, wayfarer worked fine on other compositors, for example "weston" and "labwc" and "kde". From the closed issues, "hyprland" seems to be the outlier.

**Comment by mcourteaux** [comment]
For anyone reading this in the future, I found a workaround with the windowrules in Hyprland, which makes it perfectly usable:

```
windowrulev2 = float, class:^org.stronnag.wayfarer$
windowrulev2 = float, class:^wayfarer$
windowrulev2 = size 100% 100%, class:^wayfarer$
windowrulev2 = move 0 0, class:^wayfarer$
```
