### ISSUE TITLE
Session failed - Set source not wokring

### ISSUE THREAD

**Issue by OskyEdz** [stronnag/wayfarer#7]
OS: Arch Linux x86_64
Kernel: 6.5.9-arch2-1
Window Manager: Sway
Compositor: Wayland

Wayferer version: 1.2.1 (Built from Aur package)

Expected result:
Clicking on "Set source" should allow me to selected something.

Accual result:
Clicking on "Set source" does not render anything different or show anything. 
Terminal output:
```
$ wayfarer 
Version Info: v1.2.1 (cc9ba5d, master, 2023-09-21T12:40:52+01:00)
Build Info: 2023-11-08T12:36:19Z Linux 6.5.9-arch2-1 x86_64 9PRC3D3-Archlinux, gcc version 13.2.1 20230801 (GCC)  / GNU ld (GNU Binutils) 2.41.0 / Vala 0.56.13
Session failed [GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files]
```

Troubleshooting steps:
I have restarted my machine.
I have checked pas aux and journctl for error regardin dbus - found nothing related
So it does not look like it created any service on the dbud deamond?

Are there any more steps to activate? I tried systemctl start wayfer but I could not find any service with that name.

**Comment by stronnag** [comment]
wayfarer is a **GNOME** tool (GNOME shell, mutter etc.). It may (or not) work with other Window Managers. 
It requires a `org.freedesktop.portal.Desktop` service, which should be started by the Window Manager. 
For non-GNOME WMs:
* Ensure you don't have the Gnome desktop portal installed
* Ensure you do have the desktop portal for your WM installed and started by the WM

wayfarer has been tested as working with KDE, hypr and wayfire, but is only supported in the Gnome Desktop.
